//========================================  Question 1
// Write a program that will iterate through numbers 0 to 100 and output “SK” if the
// current number is an odd number and output “Boleh” if the current number is an
// even number. Additionally, for every second even number, the output should be
// “Cemerlang” instead of “Boleh”.



var questionOne = () => {
    for (let i = 0; i <= 100; i++) {
        if (i % 2 === 0) {
            (i % 4 === 0) ? console.log("Current number is " + i + " (Boleh)") :  console.log("Current number is " + i + " (Cemerlang)") 
         } else {
            console.log("Current number is " + i + " (SK)");
          }
    }
}

questionOne()



//======Expected solution:
    // Current number is 0 (Boleh)
    // Current number is 1 (SK)
    // Current number is 2 (Cemerlang)
    // Current number is 3 (SK)
    // Current number is 4 (Boleh)
    // Current number is 5 (SK)
    // Current number is 6 (Cemerlang)
    // Current number is 7 (SK)
    // Current number is 8 (Boleh)
    // Current number is 9 (SK)
    // Current number is 10 (Cemerlang)
    // Current number is 11 (SK)
    // Current number is 12 (Boleh)
    // Current number is 13 (SK)
    // Current number is 14 (Cemerlang)
    // Current number is 15 (SK)
    // Current number is 16 (Boleh)
    // Current number is 17 (SK)
    // Current number is 18 (Cemerlang)
    // Current number is 19 (SK)
    // Current number is 20 (Boleh)
    // Current number is 21 (SK)
    // Current number is 22 (Cemerlang)
    // Current number is 23 (SK)
    // Current number is 24 (Boleh)
    // Current number is 25 (SK)
    // Current number is 26 (Cemerlang)
    // Current number is 27 (SK)
    // Current number is 28 (Boleh)
    // Current number is 29 (SK)
    // Current number is 30 (Cemerlang)
    // Current number is 31 (SK)
    // Current number is 32 (Boleh)
    // Current number is 33 (SK)
    // Current number is 34 (Cemerlang)
    // Current number is 35 (SK)
    // Current number is 36 (Boleh)
    // Current number is 37 (SK)
    // Current number is 38 (Cemerlang)
    // Current number is 39 (SK)
    // Current number is 40 (Boleh)
    // Current number is 41 (SK)
    // Current number is 42 (Cemerlang)
    // Current number is 43 (SK)
    // Current number is 44 (Boleh)
    // Current number is 45 (SK)
    // Current number is 46 (Cemerlang)
    // Current number is 47 (SK)
    // Current number is 48 (Boleh)
    // Current number is 49 (SK)
    // Current number is 50 (Cemerlang)
    // Current number is 51 (SK)
    // Current number is 52 (Boleh)
    // Current number is 53 (SK)
    // Current number is 54 (Cemerlang)
    // Current number is 55 (SK)
    // Current number is 56 (Boleh)
    // Current number is 57 (SK)
    // Current number is 58 (Cemerlang)
    // Current number is 59 (SK)
    // Current number is 60 (Boleh)
    // Current number is 61 (SK)
    // Current number is 62 (Cemerlang)
    // Current number is 63 (SK)
    // Current number is 64 (Boleh)
    // Current number is 65 (SK)
    // Current number is 66 (Cemerlang)
    // Current number is 67 (SK)
    // Current number is 68 (Boleh)
    // Current number is 69 (SK)
    // Current number is 70 (Cemerlang)
    // Current number is 71 (SK)
    // Current number is 72 (Boleh)
    // Current number is 73 (SK)
    // Current number is 74 (Cemerlang)
    // Current number is 75 (SK)
    // Current number is 76 (Boleh)
    // Current number is 77 (SK)
    // Current number is 78 (Cemerlang)
    // Current number is 79 (SK)
    // Current number is 80 (Boleh)
    // Current number is 81 (SK)
    // Current number is 82 (Cemerlang)
    // Current number is 83 (SK)
    // Current number is 84 (Boleh)
    // Current number is 85 (SK)
    // Current number is 86 (Cemerlang)
    // Current number is 87 (SK)
    // Current number is 88 (Boleh)
    // Current number is 89 (SK)
    // Current number is 90 (Cemerlang)
    // Current number is 91 (SK)
    // Current number is 92 (Boleh)
    // Current number is 93 (SK)
    // Current number is 94 (Cemerlang)
    // Current number is 95 (SK)
    // Current number is 96 (Boleh)
    // Current number is 97 (SK)
    // Current number is 98 (Cemerlang)
    // Current number is 99 (SK)
    // Current number is 100 (Boleh)